name = "pugglenaut-api"
main = "worker.ts"
compatibility_date = "2024-11-01"

[vars]
ALLOWED_ORIGIN = "https://pugglenaut.com"

[[d1_databases]]
binding = "DB"
database_name = "pugglenaut"
database_id = "bc70ecdf-8853-4ec5-8228-48e6e842dba3"

[[kv_namespaces]]
binding = "KV"
id = "d970773c23ff416b838494df9ecce612"
